### ISSUE TITLE
Single record restriction for data constructors

### ISSUE THREAD

**Issue by libscott** [purescript/purescript#1867]
One bottleneck that I've found in my code has been due to the lack of a field accessible record type that supports instances. Related issues are #1822, #1675, and maybe others. What I'd like to have is all of the following:

* Fields accessible by automatically generated `.label`s
* First class type that supports instances, especially Generic derivation.
* Javascript friendly data representation.

To illustrate:

```Haskell
newtype A = A {x::Int, y::Int}

a = A {x:1,y:2}
b = a.x -- Can't do this

a' = case a of (A r) -> r -- Have to pattern match to make a useful.
```

Regarding Javascript friendliness, the objective would be to reduce the usage of `valueN` fields in the data. The newtype solution is good until you need polymorphism. And in the case that you do need to change a `newtype` to a `data` record, you have slightly less Javascript to change. In Haskell/Purescript you have to pattern match to get at the value but in Javascript it's not so meaningful, because since there's no branching required ie `someEitherValue.value0` there's no additional safety.

Another observation:

```Haskell
data A = A {a::Int} {b::Int}
```

`A` Is not legal Haskell, but it IS legal Purescript. Would it not be a valid solution to this issue to do it the Haskell way and just allow one Object (or a sequence of non object fields) per data constructor, and skip the wrapper object entirely for this case? Ie, a `data A = A {x::Int,y::Int}` becomes a Javascript object of type `A` with properties `x` and `y`.

Edit: and since you can only have one record, you can also allow label accessors to work directly since there's no ambiguity on which record you want to access.
Thoughts?

**Comment by garyb** [comment]
> The newtype solution is good until you need polymorphism

What do you mean by that? You can do things like `newtype A b c = { x :: b, y :: c }` if that's what you mean? You're only restricted to having one constructor/one argument inside the newtype, there's no restriction on type variables.

**Comment by LiamGoodacre** [comment]
> Fields accessible by automatically generated .labels

I feel this is of limited use and mostly problematic.  Just because something is declared as a newtype doesn't mean any other parts of your code should depend on that (potentially temporary) implementation detail - especially when consuming from JavaScript.

> First class type that supports instances...

Can you elaborate on this?  I can't figure out what you mean.  Are you talking about instances for structural record types? - because that doesn't really make much sense.

**Comment by libscott** [comment]
> What do you mean by that?

I mean that when you need to change:

```Haskell
newtype Result = Result {a::Int}

-- to:

data Result = ResultA {a::Int} | ResultB {b::Int}
```
Your corresponding JS needs to change as such:

```Javascript
var result = psFunc();
console.log(result.a);

// to

var result = psFunc()
if (result instanceof ResultA) console.log(result.value0.a)
else                           console.log(result.value0.b)

// alternative:

var result = psFunc()
if (result instanceof ResultA) console.log(result.a)
else                           console.log(result.b)
```

I suppose what I'm saying is that the intermediary object doesn't add anything to your Javascript experience, and that perhaps you could make your purescript and javascript data API more friendly by limiting the number of top level objects per data decleration to one, and getting rid of that intermediary object, as in above alternative code.

> I feel this is of limited use and mostly problematic. Just because something is declared as a newtype doesn't mean any other parts of your code should depend on that (potentially temporary) implementation detail - especially when consuming from JavaScript.

There's 2 things here; one is the usefulness of being able to use record labels directly on `newtype` / `data` values, which I feel is useful, it will reduce the need for intermediary values / case statements which can clutter the namespace and/or add to the complexity of your code.

The other issue is the Javascript ABI or "AJI" (Application Javascript Interface) and again I think it's just an opportunity to reduce noise and remove one of the variables that a coder has to deal with, ie, whether or not the data is in a `value0` or not. And yea it's not a big deal, the nicer thing is the first one, but when there's deadlines and technical debt mixed in then it could be nice not to have to worry about `value0`.

> Can you elaborate on this? I can't figure out what you mean. Are you talking about instances for structural record types? - because that doesn't really make much sense.

By "first class type", I meant a `newtype` / `data` as opposed to a type alias, for which you can't create instances. So, the following is what I'm describing:

```Haskell
data Foo = Foo {bar::Int}
instance showFoo :: where show (Foo {bar}) = "Foo bar=" ++ show bar

let foo = Foo {bar:1}
print foo
print foo.bar
```

**Comment by hdgarrood** [comment]
I'm not keen on the "limiting the number of top level objects to one" approach, especially if the goal is to make it easier to pattern match on PureScript types in JS. x.value0 is an implementation detail that your code shouldn't ever really be depending on. Also, pattern match on PS types in PS! You get exhaustivity checking, type checking, etc.

I think I'd rather keep predictable and simple code for data types over aiming for idiomatic JS interfaces to PS. The latter can always be achieved in "userland" with a small amount of glue code.

**Comment by user471** [comment]
>By "first class type", I meant a newtype / data as opposed to a type alias, for which you can't create instances. So, the following is what I'm describing

But what would be the type of 
```
getBar x = x.bar
```
?
On the one hand it should be ``` {foo::a} -> Int``` but on the other hand it should also accept ```data Foo```
I suggested two approaches in https://github.com/purescript/purescript/issues/1822
1) More restricted version of type synonym aka newtype without constructor.
```
typename Foo = {bar :: Int}
instance showFoo :: Show Foo where 
  show x = "Foo bar=" ++ show x.bar
```
2) Or implicit newtype
```implicit newtype Foo = Foo {foo :: Int}```
In both cases type of ```getBar``` would be ``` {foo::a} -> Int``` but it would be possible to use this function with `Foo` without unwrapping.

**Comment by libscott** [comment]
> I'm not keen on the "limiting the number of top level objects to one" approach, especially if the goal is to make it easier to pattern match on PureScript types in JS.

Well, it would be nice, but the bigger goal IMO would be to allow using labels on wrapped values. Limiting the number of records to one ala Haskell would seem to make the `valueN` labels redundant, except in the case of `data Foo = Foo Val Val Val`, which is why I suggested it.

**Comment by libscott** [comment]
> On the one hand it should be {bar::Int} -> Int but on the other hand it should also accept data Foo

Not sure I agree that it should accept both.

**Comment by user471** [comment]
> Is there a strong use case?

Case of what? If you mean functions like `getBar` then yes, there is 'lens` library.

**Comment by garyb** [comment]
I can't really see any pleasant way to allow accessors for records in `newtype`/`data`, but the suggestion to move the properties of a record onto the generated "class" (in JS terms) actually seems pretty reasonable (so, no `value0`, just named properties on the object), as we'd get a performance benefit from doing so also.

However, I'm not at all in favour of the restriction of having one record per constructor, as it's pretty arbitrary. We have some JS-leaning choices in the language, but we (or I at least) don't wan't to be restricted to just whatever makes "good" JS. If that were the case then we wouldn't have curried functions most likely.

So if we were to do it, and just apply it in the appropriate case, it still wouldn't be obvious when you need a `value0` or not.

**Comment by LiamGoodacre** [comment]
@garyb Are you saying something like, just for the special case of constructors with a single argument that is fixed to be a record:

~~~purescript
-- given purescript
data A x = A { x :: x }
unA :: forall x. A x -> { x :: x }
unA (A o) = o
~~~
~~~javascript
// generated javascript
// new                                  // current
var A = (function () {                  var A = (function () {
    function A(record) {                    function A(value0) {
        this.x = record.x;                      this.value0 = value0;
    };                                      };
    A.create = function (record) {          A.create = function (value0) {
        return new A(record);                   return new A(value0);
    };                                      };
    return A;                               return A;
})();                                   })();
var unA = function (_0) {               var unA = function (_0) {
    return { x: _0.x };                     return _0.value0;
};                                      };
~~~

Because for multiple properties that looks like a lot of copying on construction/destruction so I'm not sure it'd be a performance benefit?

**Comment by LiamGoodacre** [comment]
Or maybe it is a big improvement http://jsperf.com/psc-copy-props

**Comment by libscott** [comment]
> However, I'm not at all in favour of the restriction of having one record per constructor, as it's pretty arbitrary. We have some JS-leaning choices in the language, but we (or I at least) don't wan't to be restricted to just whatever makes "good" JS. If that were the case then we wouldn't have curried functions most likely.

FWIW, my take on the Haskell "one record per constructor" limitation was just so that you could address properties unambiguously. Personally I think it is a benefit. As for the JS api, I made some examples of different transitions and how they affect the data API; in my project, I'm using Purescript to do some parsing and other pure stuff where I want types and lots of safety, but the UI gruntwork is done in Javascript, which is about 5x more bug prone because it's completely dynamic and untested. I imagine this is a common situation in any shop where they use Javascript, some developers advocate using Purescript for module X because of the suitability of it to do complicated things compared to Javascript, and over time the API will evolve. Making changes less surprising and less bug prone == brownie points.

### Example 1, no value0 in case of single record

```Haskell
data Foo = Foo {bar::Int}
type Result = Foo -- unwrapped

-- to

data Foo = Foo {bar::Int} {baz::Int} -- doesn't encourage you to think about naming early on
type Result = Foo -- Result still unwrapped
```

Corresponding JS:

```Javascript
var result = psFunc(),
    bar = result.bar;

// to

var result = psFunc(),
    bar = result.value0.bar, // somewhat surprising change in data structure
    baz = result.value1.baz; // if you want to improve naming in the future you will have to change this again.
```

### Example 2, Single record restriction, labelled values

```Haskell
data Foo = Foo {bar::Int}
type Result = Foo -- Result is unwrapped

-- to:

data Foo = Foo {bar::Int}
data Baz = Baz {quux::Int}
data Result = Result {foo::Foo,baz::Baz} -- Result is wrapped, intent is explicit
```
JS:
```Javascript
var result = psFunc(),
    bar = result.bar;

// to

var result = psFunc(),
    bar = result.foo.bar,
    qux = result.baz.qux; // data structure has changed, less likely to change again in future because we've already introduced labels
```

### Example 3, Single record restriction, unlabelled values

```Haskell
data Foo = Foo {bar::Int}
data Result = Result Foo -- Foo is unlabelled

-- to:

data Foo = Foo {bar::Int}
data Baz = Baz {quux::Int}
data Result = Result Foo Baz
```

JS:

```Javascript
var result = psFunc(),
    bar = result.value0.bar; // value0 is expected since Foo is unlabelled

// to

var result = psFunc(),
    bar = result.value0.bar,
    qux = result.value1.qux; // data structure didn't change.
```

I think the single record restriction is better in terms of being less surprising and encouraging thoughtful nomenclature.

**Comment by paf31** [comment]
I'd really like to avoid changing the runtime meaning of data based on usage. I don't even know how that would be safe.

If the initial goal was to have Haskell-like records, why not use lenses?

**Comment by libscott** [comment]
> If the initial goal was to have Haskell-like records, why not use lenses?

Personally I'm quite familiar with lenses, but I decided not to use them yet, because a) Purescript's compiler errors are still a bit cryptic in some cases, b) I didn't want to inflate the generated Javascript which I would prefer to keep lean where possible, to make compiled JS faster to download and c) easier to debug.

I would happily use them if they were baked into the langauge, that would be way cool IMO, but thats another story...

**Comment by paf31** [comment]
> I would happily use them if they were baked into the langauge, that would be way cool IMO, but thats another story...

I agree it'd be cool, but I'm not sure how to implement them while keeping things composable. What would the runtime representation be?

**Comment by libscott** [comment]
> I agree it'd be cool, but I'm not sure how to implement them while keeping things composable. What would the runtime representation be?

Something close to invisible? The idea is to reduce cognitive load.

**Comment by libscott** [comment]
Right now I'm working with JS and it would be convenient if the constructor was a key, ie:

```Javascript

if (result.Left) {

**Comment by paf31** [comment]
Votes please. :-1: from me.

**Comment by hdgarrood** [comment]
:-1: from me too, sorry. If you want to make purescript code accessible and idiomatic to use from JS, we already have the tools for doing this in 'userland'. For example, you can pattern match in JS by exporting functions like `maybe` or `either` for your data types. Also, i think there are too many different options for exactly how you approach idiomatic JS interfaces for us to pick one and 'bless' it by building it into the compiler.

**Comment by garyb** [comment]
:-1: although I'm sympathetic to the point that point that generated code is less than ideal to work with in JS, I don't think it justifies this. I think there are other options for doing so (like providing a "compatibility module" layer in between the idiomatic PS and the JS that makes things more convenient from a JS point of view) that don't result in having some strange rules for the PS definitions.

**Comment by libscott** [comment]
Ah well, I thought I'd provide some feedback, thanks for considering anyhow :). I guess I'll close this!
