### ISSUE TITLE
Permit a single open import without a warning

### ISSUE THREAD

**Issue by tfausak** [purescript/purescript#1869]
Or: "What happened to `(..)`?"

Let's say I have a module `B` that should reexport everything from `A`, like so:

``` purescript
-- A.purs
module A where data X
-- B.purs
module B (module A) where import A
```

Compiling that with PureScript 0.8.0, I get the following warning:

```
Warning found:
in module B
at /private/tmp/example/src/B.purs line 1, column 27 - line 1, column 34

  Module A has unspecified imports, consider using the explicit form:

    import A (X)



See https://github.com/purescript/purescript/wiki/Error-Code-ImplicitImport for more information,
or to contribute content related to this warning.
```

I used to be able to explicitly get open imports by saying `import A (..)`, but that's a syntax error now.

``` purs
-- B.purs
module B (module A) where import A (..)
```

```
Error found:
at /private/tmp/example/src/B.purs line 1, column 37 - line 1, column 37

  Unable to parse module:
  unexpected ..
  expecting identifier, (, proper name, "class", "module" or )


See https://github.com/purescript/purescript/wiki/Error-Code-ErrorParsingModule for more information,
or to contribute content related to this error.
```

What's the right way to do this?

**Comment by natefaubion** [comment]
The `(..)` syntax was removed. The warnings are so to strongly discourage open imports of any kind. When open imports are allowed, adding a function or definition to exports has to be a breaking change, because it can potentially cause clashes with downstream libraries.

For example:
```purescript
module A where
  data Foo

module B where
  data Bar

module C where
  import A
  import B
```

As the author of library `A`, maybe I'll decide to add an export for a new internal data structure that I want to make public, and it happens to be called `Bar`. I would not consider this a breaking change, since I'm only adding to the exported API. So I release it with a patch version. But downstream module `C` is using open imports, and updates to the latest patch release and all of a sudden their code is broken :(

The answer is just to list all your imports.

**Comment by natefaubion** [comment]
That said, it _is_ really obnoxious with `Prelude` type modules. `Prelude` rarely changes, and if any of the API were to change it should at _least_ be a minor bump.

**Comment by tfausak** [comment]
I understand what you're saying, but that only really applies when you have both open exports and imports. I didn't specify when I created this issue because it wasn't necessary to recreate, but I typically use explicit exports rather than imports. For example, [`Neon.Class`](https://github.com/tfausak/purescript-neon/blob/v0.3.0/src/Neon/Class.purs) exports 28 other modules. Each of those, like [`Neon.Class.Add`](https://github.com/tfausak/purescript-neon/blob/v0.3.0/src/Neon/Class/Add.purs), explicitly list their exports. Doing it in both places is a huge pain for me and not something I want to do.

**Comment by natefaubion** [comment]
> I understand what you're saying, but that only really applies when you have both open exports and imports. 

That's not quite true. I think for `psc` to make that distinction it would have to have some notion of the packages (packages should be able to openly import from themselves because otherwise it wouldn't have compiled in the first place). As far as `psc` is concerned, each module could be coming from completely unrelated packages, and is therefor unsafe to do so.

**Comment by michaelficarra** [comment]
@tfausak That's not at all the case. The problem arises whenever you have open imports, regardless of your exports.

**Comment by tfausak** [comment]
Y'all are right, of course. I am considering this from the perspective of a single library. When you get other libraries involved, the case explained by @natefaubion is easily possible. 

Within a package, explicitly listing exports and imports is annoying.

**Comment by garyb** [comment]
It is a bit, but that's why the warning prints the fix.

**Comment by michaelficarra** [comment]
@tfausak You can choose to qualify your imports instead: `import A as A`. Hopefully in the future when we have no more pre-0.8 code around, we can change `import A` to be a shorthand for that.

**Comment by tfausak** [comment]
I find the warning unsatisfactory because if I want to add something to `Neon.Class.Add` I have to add it to both the export list and the import list in `Neon.Class`. 

The qualified import is a good trick. I know HLint usually recommends doing `import A.B.C as X` so that your export list only has a single `module X` in it. I typically don't do that because it confuses Haddock, but I haven't checked what `psc-publish` generates for that.

**Comment by garyb** [comment]
I know what you mean. I don't _like_ this either, but it's definitely the least bad solution we have right now. We have actually been bitten by upstream library changes breaking their dependants, if these warnings are heeded that will never happen, which seems like a worthwhile tradeoff.

**Comment by paf31** [comment]
And remember, you can always filter warnings using `purescript-psa`. The decision was made to not provide that functionality in the compiler, since we try to push these sorts of things into tools where possible.

**Comment by tfausak** [comment]
That's good to know. I would prefer to build my libraries without warnings, though.

**Comment by tfausak** [comment]
I ran into a few more annoyances while trying to work around this.

- The qualified import trick does not work if you want to re-export multiple modules. `module A (module X) where import B as X; import C as X` gives a warning.

- The qualified import trick does not work if you hide imports. `module A (module B) where import B hiding (X) as B` gives a warning.

- There is apparently no solution for importing a prelude style module without warnings. For instance, [this spec](https://github.com/tfausak/purescript-neon/blob/06dd7ec2eaad9e94f2b504a578d3377ee9cf218b/test/Neon/Class/SubtractSpec.purs#L3) imports a common `Test.Helper` module that is intended to be used with open imports. That gives a warning. It's annoying to work with (even with the copy-pastable code in the warning) because I'd have to change the import if I added or removed a `pending` spec, for example. (I don't want to import it qualified because I think qualified operators are hideous.) 

I see I missed #1742, which removed the `import A (..)` syntax for open imports. I wish there was still a syntax for open imports. I can't think of another language that doesn't have them. Every example on the PureScript homepage and on Try PureScript! would emit at least one warning because of this.

**Comment by hdgarrood** [comment]
I'm beginning to think the answer could be to make the compiler aware of packages and to only emit the warning for modules defined in different packages.

**Comment by tfausak** [comment]
That would be a good way to handle the scenario that I'm dealing with now. But how should you import the `Prelude` (or `Neon`) without a warning?

**Comment by garyb** [comment]
Just to address one minor point: you could import operator(s) explicitly and then use a qualified import for the rest of the module.

**Comment by garyb** [comment]
As for the other point, there is no safe way to allow open imports of any module, even if it is `Prelude` or `Neon`, unless we decide to start treating additions to a module as a breaking change.

**Comment by tfausak** [comment]
I don't think adding exports should be a breaking change. But it's also not a patch-level change, as @natefaubion originally suggested. It would be a minor version change, at least according to semver. 

For what it's worth, I have never run into this particular problem. I see how it can happen, but it seems exceptionally rare. 

Can this only be a warning if you reexport a module that you import openly?

**Comment by hdgarrood** [comment]
Another thing that's just occurred to me - I think the usefulness of this warning depends on the code you're writing. For an application, you probably don't want it. For core libraries, you almost certainly do. So I think the answer may be to come up with a good set of defaults in psa; for example, I think this particular warning should be opt-in.

**Comment by garyb** [comment]
We have run into this problem, that's why it's a concern :smile:. Even if not, the fact that a minor version bump _can_ break code without this warning makes it a concern.

The problem has nothing to do with what a module exports, it arises with open imports due to the possibility of multiple values with the same name being brought into the same scope. If you use explicit imports then this can never happen. If you import two modules qualified with the same name, they're also being imported into the same scope, which is why it is a warning to do so without being explicit about what you're importing for both too. Import `hiding` is another form of importing implicitly, as again it only specifically rejects some things while importing everything else.

The only possible situation in which it would be safe to import openly is: if the module has no members of its own, and only has one import. So basically a situation that is entirely useless.

**Comment by hdgarrood** [comment]
@taylorfausak the problem with making additions a minor change and allowing open imports simultaneously is that a minor upgrade can break your package by introducing a name clash.

**Comment by garyb** [comment]
@hdgarrood even that's not safe really, as if Prelude changes or whatever it could break code in your app, unless the app sticks to exact versions rather than ranges.

**Comment by hdgarrood** [comment]
Yes, but I'd still so much sooner have to periodically fix this sort of break while updating to new minor versions of my dependencies than have to fiddle with import lists almost every time I change my code. I also think sticking to exact versions is usually the right approach for applications anyway.

**Comment by tfausak** [comment]
> I'd still so much sooner have to periodically fix this sort of break while updating to new minor versions of my dependencies than have to fiddle with import lists almost every time I change my code.

:+1: :heavy_multiplication_x: :100:

**Comment by garyb** [comment]
@tfausak he's talking about apps there though, not libraries.

**Comment by tfausak** [comment]
Fair enough, but I'm talking about libraries as well as apps.

**Comment by garyb** [comment]
Yeah I know, but I don't think breaking dependants is an acceptable solution :)

**Comment by tfausak** [comment]
The main problem for me is that there's no way for me to convince the compiler that I know what I'm doing. I understand the warning, I understand the problems that can arise, and I want to do it anyway. Why can't I? 

I see https://github.com/purescript/purescript/issues/1742#issuecomment-167578163 suggests making `import X` mean `import X as X` (i.e., making the default import qualified). I am fully in favor of that. In fact, I think [Elm's imports](http://elm-lang.org/docs/syntax#modules) are my favorite. But the key point to me right now is that it's possible to do an open import without warnings in Elm. 

Obviously the intent of warnings it to encourage people to fix them. Do you really want people writing `import Prelude ((+), bind, etc)` instead of `import Prelude (..)`?

**Comment by hdgarrood** [comment]
Yeah, I was only talking about applications.

If we did make the compiler aware of packages, and then turned off the warning for open imports from the same package, you could then define an internal prelude module for your package which re-exports everything in the real Prelude (and maybe a couple of extras if you want to), and then you could have an open prelude-style module import without generating this warning, and I think that could alleviate most of the pain. Additionally, I think tooling which automatically adjusted import lists for you could help a lot too. Ideally I guess we would have both of these things.

**Comment by AppShipIt** [comment]
Where do I read to understand imports in PureScript? It seems like they're unqualified by default (whereas Elm's are qualified as pointed out by @tfausak), no longer provide syntax to use unspecified without warning, essentially pushing users to either qualify or specify, motivated to prevent the chance of future collision.

Clashing names is why I thought minor versions exist in semver. I don't see why code should be noisy to prevent a break resulting from a minor change any more than a major one. Where it's a concern I assume users don't import unspecified or limit updates to patch level.

If all those are correct I'm missing how to use future preludes without warnings and how PureScript can address Stephen Diehl's [criticism](http://www.stephendiehl.com/posts/production.html) of Haskell in production:

> In practice any non-trivial business logic module can very easily have 100+ lines just of imports, and frankly it gets tiring. One common way of abstracting this is by rolling a custom prelude using module reexports.

**Comment by garyb** [comment]
Minor changes aren't supposed to break code though, if you use a version like `^1.0.0` that means `1.1.0` is also acceptable. If that introduces a new member that clashes, then it becomes a breaking change.

The criticism is valid, but I'll take a predictably non-breaking build over something that is occasionally tiring. The custom project-specific prelude approach may well become viable if we make the compiler aware of packages in the future.

**Comment by AppShipIt** [comment]
If you want to restrict to patch level changes can't you also impose `~1.0.0`? Wouldn't it break any language with open imports by nature? While I understand that's not a tradeoff you personally want to make at work I don't understand why that necessitates all language users to code with a worse experience. It's not just about tooling it's readability and evangelizing users. At the heart of language design should not only be simplicity and security but developer experience. Ultimately imports are one of the few things Elm did that I liked (albeit bundling their prelude is less nice). By default everything is qualified, unqualified is specified, and unqualified unspecified imposes a little noise to opt into. But warning for every `import Batteries` (or `import Batteries exposing (..)` or whichever syntax) is a nonstarter ☹️

**Comment by tfausak** [comment]
> If you want to restrict to patch level changes can't you also impose ~1.0.0?

Exactly. This problem is already solved by tooling. If you're doing an open import of some other library *and* your specified version range for that library allows additions, you're going to have a bad time. The fix is not to disallow open imports; it's to specify a better version range. 

If the compiler is aware of packages and y'all address this problem that way, you're forcing every package to define its own prelude in order to build without errors. That would be very annoying, especially since many of them would end up looking like this:

``` purescript
module My.Prelude (module Export) where import Batteries as Export
```

**Comment by AppShipIt** [comment]
I see @garyb's point. IIUC `import Batteries (..)` was essentially replaced with a bare import and a warning. My big ask is twofold: how to preserve the beginner's experience and 2) how to prevent reading code from devolving into scrolling past imports or weird formatting conventions when they import multiple lines of identifiers from a single package.

**Comment by AppShipIt** [comment]
One more thought. When we have a package manager that enforces semver, could it also impose patch level granularity upstream? I.e. if I left Prelude open when I port Foldl, could the package manager require clients to adhere to the same minor version? If that's an eventual solution I'd feel more comfortable.

**Comment by hdgarrood** [comment]
The intention was always that switching individual warnings on and off would be controlled by tooling, and in fact it is possible to do this today with purescript-psa.

I think we can all agree that this warning makes sense in some, but not all, cases. Definitely it's right for core libraries. It's probably right for other libraries, too. It's probably not necessary for applications, though. Therefore the right approach seems, to me, to be leaving the compiler as-is, at least with respect to this warning.

Restricting to patch-level changes seems like a cop-out to me - if we always did that, what would be the point of the minor version component, of distinguishing additive and breaking changes? It would also increase the risk of dependency conflicts. Maybe npm land can get away with that because of the dependency nesting, but we can't do that here.

Additionally, as previously noted, there's still room for tooling that intelligently adjusts imports for you, which would be useful even if you had chosen to ignore this warning.

Finally, @tfausak, the example package specific prelude you have there wouldn't really work, as if you just reexport everything you might as well just be importing Batteries directly. You'd need to explicitly list everything you want to reexport in order to defend against future additive changes (that's what I was imagining when I suggested it).

**Comment by garyb** [comment]
We may as well not be using semver if `~` ranges are the answer, since then there are only two kinds of changes: breaking and patch.

The way I see this whole thing is, if you're writing a library then the only way for it to be a good citizen of the ecosystem is to fix all warnings, and this one is actually especially important for that case. If you are not working on a library then this error is safe to ignore, as then it's your own fault when a library changes and breaks your build - at least you won't be breaking anyone elses code. You can actually do this now with `purescript-psa` too.

It's a restriction we could possibly lift if we introduced our own package manager, as then we could refuse to accept submissions that break this rule, and not have to provide the warning for normal compilation use.

This will probably be my last post in this thread as I'm not sure what else I can say without repeating myself further. :wink:

**Comment by AppShipIt** [comment]
As succinctly as possible:

I get your concern and it's legitimate. I'm searching for a nicer resolution. Code is intended to convey intent. Listing out every identifier I'm using is ancillary, redundant (the compiler knows), and moreover manual (even "tiring"). If a tool can do it then a tool shouldn't need to do it. Call it noise or incidental complexity but it's a smell.

Your concern is opening imports introduces conflicts with introduced identifiers. My concern is making it a warning will encourage ugly code (a perfect example is `P.<?>` in the Haskell parser). What if (not as a proposal but to turn the conversation toward different ideas that acknowledge and address both issues) user identifiers always shadow imported ones but warn when they conflict??

**Comment by garyb** [comment]
Identifiers can conflict when imported from different modules also:

```
module C

import A
import B

g x = f x true -- I wanted A.f, but oops, B now exports it too
```

**Comment by garyb** [comment]
Regarding "if a tool can do it then I shouldn't have to", I definitely agree in principle, but that's missing the "when" in this case: it can only be done at the time you're authoring the library, as the imports/exports need fixing at that moment in time, with the exact dependency versions you have.

Again this is in theory something that a package manager could help with, although this variation would require a central code repository as it would have to modify the source code when you publish a package to lock down the identifiers. I don't that central repository approach was the way we were looking at going though.

**Comment by hdgarrood** [comment]
I don't believe listing out every identifier is redundant, given that we are depending on version ranges of other libraries, when multiple modules will often export values with the same identifier (eg: try searching Pursuit for `filter` or `replicate`), and especially given that ranges will usually include future versions which don't yet exist at the time of publishing.

Explicit import lists are also incredibly helpful for finding where an identifier was imported from, and I think we should usually be optimizing for reading rather than writing.

**Comment by tfausak** [comment]
I have yet to hear a good solution to the problem of importing a prelude without warnings. I don't consider configuring `purescript-psa` to be a good solution because either (a) I won't do that and I'll start to ignore warnings altogether or (b) I have to disable that warning in literally every project I work on. 

I agree that explicitly listing imports (or using qualified imports) is a good thing. But the whole point of a prelude is that everyone should be familiar with it. Doing `1 Prelude.+ 2` or `import Prelude ((+)); 1 + 2` is ridiculous. 

I also think that not having a solution for the extremely common case of re-exporting modules is absurd. How many packages have a top-level module for convenience that simply re-exports stuff from other modules? I know I use that pattern a lot. I suspect many other package authors do as well. 

Like @garyb I feel like I'm repeating myself now.

**Comment by paf31** [comment]
> I agree that explicitly listing imports (or using qualified imports) is a good thing. But the whole point of a prelude is that everyone should be familiar with it. Doing 1 Prelude.+ 2 or import Prelude ((+)); 1 + 2 is ridiculous.

Could some sort of import macro or preprocessing step solve this then? Or project-specific default imports?

**Comment by garyb** [comment]
> I also think that not having a solution for the extremely common case of re-exporting modules is absurd. How many packages have a top-level module for convenience that simply re-exports stuff from other modules? I know I use that pattern a lot. I suspect many other package authors do as well. 

Then just fix the warnings, it's not like it's hard when the compiler tells you the code you need to paste in :stuck_out_tongue_winking_eye:. I have no problem [with this](https://github.com/purescript/purescript-prelude/blob/0.8-updates-moduleified/src/Prelude.purs), it's not like you're constantly messing with the exports. Or if you are, just ignore the warnings until you're ready to publish the library.

That's the way I work with this in general actually, write with mostly open imports first and then just fix all warnings when I'm done.

I guess I can think of one potential option to allow an open `Prelude` import: special rules for when there is a single open import in a module. If there is a conflict between an explicit import or declaration and something in the implicit import always take the explicit/declared value and just raise a warning about name shadowing rather than a name conflict error. If two open imports are used then go back to warning about all implicit imports.

**Comment by hdgarrood** [comment]
> Could some sort of import macro or preprocessing step solve this then?

I'd much rather make use of the existing machinery to achieve this (see my previous proposal re package-specific prelude modules) than add new stuff. Macros or preprocessing sound like they would be a nightmare for tooling, and I'd guess it would be about the same amount of work to do it safely either way.

I think the single-open-import approach sounds quite promising.

**Comment by AppShipIt** [comment]
> Identifiers can conflict when imported from different modules also:

@garyb Ah thanks. I think we're on the same page.

> try searching Pursuit for `filter`

Yep polymorphic fail.

> I think we should usually be optimizing for reading rather than writing.

Exactly except they're mutually inclusive. My previous example of _qualifying_ muddling reading was `P.<?>` in the parser and of _specifying_ was Stephen's quote on scrolling through production Haskell. One of the barriers to entry for me starting PureScript was the list of imports necessary to accomplish seemingly basic tasks.

> Explicit import lists are also incredibly helpful for finding where an identifier was imported from

As is <kbd>command+click</kbd> which is used in OOP tooling. I've never heard complaints that their imports weren't explicit enough. If anything that's the argument I've heard (nonsensically to me) against type inference.

I don't have a solution. I understand psa helps for now. But there's already a long list (including tools) for a beginner to just get started with PureScript (the impetus for my personal projects). And a warning will dictate conventions which are less ideal for non-library authors (ultimately the predominant case).

**Comment by tfausak** [comment]
I would be happy with allowing a single open import. That makes importing preludes easy and discourages you from importing anything else unqualified. 

That doesn't solve my other problem of re-exporting stuff, but it seems like I'm losing that battle.

**Comment by garyb** [comment]
> That doesn't solve my other problem of re-exporting stuff, but it seems like I'm losing that battle.

Yeah, I just can't see any safe way to fix that without the compiler being aware of packages, as the only case it's safe is if all the modules are defined in the current package.

**Comment by AppShipIt** [comment]
Thanks for for the discussion 🙏 I really appreciate y'all's thoughts besides everything else you're doing this weekend. Hypothetically:

1. > @garyb: one potential option to allow an open Prelude import: special rules for when there is a single open import in a module. If there is a conflict between an explicit import or declaration and something in the implicit import always take the explicit/declared value and just raise a warning about name shadowing rather than a name conflict error. If two open imports are used then go back to warning about all implicit imports.

  That sounds practical!

2. > @hdgarrood: If we did make the compiler aware of packages, and then turned off the warning for open imports from the same package,

  <q>Single open imports</q> covered your use case but would this resolve @tfausak's original issue i.e. no warning if he only rexports internal packages? Could <q>single open imports</q> and <q>package internal imports</q> be used in tandem? Too contrived?

  > @hdgarrood: Additionally, I think tooling which automatically adjusted import lists for you could help a lot too. Ideally I guess we would have both of these things.

  Worth tracking in the plugins. @nwolverson is starting a library written in PureScript shared between Atom, VS Code, and potentially my JS Bin fork.

3. > [@garyb] suggests making `import X` mean `import X as X` (i.e., making the default import qualified).

  This sounds desirable as `import X` unqualified will typically produce a warning? What about:

  * Names in parens: unqualified or not (like Elm's `exposing`). Not in parens: qualified only.
  * `import Neon (..)`: unqualified + unspecified.
  * `import Neon as N`: status quo.

  E.g. `import Neon as N (Add)` would expose `Add`, `N.Add`, and `N.Subtract`, but not `Neon.Add`.

Are any of these worth opening separate issues?

**Comment by paf31** [comment]
I'm a bit late, but I'd like to add: warnings indicate that something is potentially wrong, but not necessarily that something _is_ wrong. So I would personally rather see a rich collection of data on what I might have done wrong, so that I can collect it, filter it, etc. and learn about my code.

As a library author, I'm more incentivized to try to fix some or all of the warnings before shipping, but an app author might be fine with just silencing everything.

Maybe I missed this above, but why is seeing a warning an issue in the first place?

Also, I'm not sure I'm particularly enthusiastic about the compiler knowing about package structure.

**Comment by AppShipIt** [comment]
> warnings indicate that something is potentially wrong, but not necessarily that something is wrong.

Every enterprise I've worked for has allowed warnings to accumulate in the thousands. Eliminating warnings has been essential for their utility to me. If we're proposing using psa like a linter then it needs increased logging granularity. IntelliJ platform IDEs have long featured [inspections](https://www.jetbrains.com/idea/help/configuring-inspection-severities.html) with levels including `error`, `warning`, `weak warning`, and `info`.

But my interpretation of a compiler warning is an error that hasn't happened yet. Deprecations are warnings. Multiple open imports which can break downstream on a nonbreaking change are legitimately warnings. `import Prelude` is definitely _not_ a warning.

> I'm not sure I'm particularly enthusiastic about the compiler knowing about package structure.

So 2) @hdgarrood's proposal is out, but I'm still interested in 1) @garyb's <q>single open import,</q> and feel it's incumbent 3) changing the semantics of `import` so its default usage isn't warned.

**Comment by hdgarrood** [comment]
I'm only advocating a very weak form of the compiler knowing about packages: when invoking psc, rather than supplying a few huge globs that cover everything, we supply a list of package name/glob pairs.

We also need to address the issue that two separate packages can define modules with the same name eventually, so I think we have to do something like this anyway.

**Comment by hdgarrood** [comment]
@AppShipIt psa does have a command line option which lets you ignore individual warnings, you just add `censor-codes=ImplicitImport` to ignore all open import warnings.

**Comment by AppShipIt** [comment]
I know. My point is it isn't categorical and that all open imports aren't warnings.

**Comment by hdgarrood** [comment]
Sorry, I don't follow.

I'm not sure that "error that hasn't happened yet" is a great perspective for compiler warnings anyway. Consider shadowed variable names and unused bindings. They might be errors which have already happened (and which only manifest at runtime), or they might not be errors and might never end up causing problems. In my book they're both extremely useful warnings to have, though, and they should be fixed in either case.

**Comment by AppShipIt** [comment]
> useful warnings…should be fixed in either case.

I'm fine with that definition. It still doesn't apply to `import Prelude`.

**Comment by hdgarrood** [comment]
`import Prelude` might never end up causing problems, but equally, it might cause problems which should have been completely avoidable, so I think it does apply.

The single open import idea would solve this anyway, as far as I can tell. Do we all agree that it's worth a try?

**Comment by AppShipIt** [comment]
> The single open import idea would solve this anyway

* doesn't apply to `import Prelude` if it's alone

I'm ready to open an issue for it. That leaves my concern about changing the semantics of `import X` to `import X as X` and corresponding proposal. Worth issues for each?

**Comment by paf31** [comment]
No, let's please keep the issues to a minimum. Let's choose a path and rename this one.

**Comment by AppShipIt** [comment]
@paf31 How do you feel about <q>single open import</q>? @garyb suggested it and @hdgarrood is on board. @garyb also suggested changing the meaning of `import X` (warning) to `import X as X` (no warning and akin to Elm). I offered the following clarifications:

> * Names in parens: unqualified or not (like Elm's exposing). Not in parens: qualified only.
* import Neon (..): unqualified + unspecified (like 0.8.x).
* import Neon as N: status quo.

**Comment by garyb** [comment]
`import X as X` is unnecessary actually, as you can already reference `X.y` without requiring an import at all. At the time I suggested it we had discussed dropping that ability (for performance reasons) but we didn't end up needing to do that in the end.

**Comment by AppShipIt** [comment]
@garyb Oh my bad I thought I had tried that. But if the way I want to use `X` is qualified as `X` is `import X as X` the only way to do so without a warning?

**Comment by garyb** [comment]
Yeah, I think so.

**Comment by AppShipIt** [comment]
I prefer your suggestion with `import Prelude (..)` being explicit, willing to tackle it `DIY` (especially since half the work is reverting a commit), but not passionate if y'all dislike it.

**Comment by garyb** [comment]
Oh, I meant to respond to your suggestion about

``` purescript
import Neon as N (Add)
```

Although this would be super useful to have with it working the way you outlined, I worry that it would be confusing given that we already have:

``` purescript
import Neon (Add) as N
```

Which means something else, and is actually useful. It's required for cases where you import more than one module into N, as that suffers from the open-modules problem where conflicts can arise if the imports are unspecified. And also is useful for some re-export tricks, where you import some values from a module but then want to re-export different values.

**Comment by paf31** [comment]
> We also need to address the issue that two separate packages can define modules with the same name eventually, so I think we have to do something like this anyway.

What about allowing _filename qualified_ imports, rather than package qualified? The compiler is aware of files, but not packages.

So, under the single open import suggestion, names in a closed import would shadow names in an open import without warnings? I'm not sure if I like that or not, since I think we already have enough ways to import something without beginners having to learn another rule, but it seems like a decent compromise. What if you have multiple open imports? Would they be shadowed too?

**Comment by AppShipIt** [comment]
> I worry that it would be confusing given that we already have:

@garyb I didn't consider that I'll noodle on it today.

> What if you have multiple open imports? Would they be shadowed too?

Not according to @garyb:

> If two open imports are used then go back to warning about all implicit imports.

**Comment by garyb** [comment]
> So, under the single open import suggestion, names in a closed import would shadow names in an open import without warnings?

No, it would warn if that occurred but it wouldn't error, which will happen currently.

**Comment by garyb** [comment]
Oh sorry, if they're just shadowed they won't error currently, but that's the main thing I propose to change to make this single-open-import thing fix "The Problem". If `x` is in scope _and used_ from both an implicit and explicit import the implicit version will be warned about, whereas currently conflicting members become an error regardless of how they arrived in the module.

**Comment by paf31** [comment]
Seems like a reasonable solution. What are the downsides? It possibly makes more work for tooling, but that is a solvable problem. Can we think of any ways in which a dependency change could lead to breakage, which wouldn't be a warning?

**Comment by garyb** [comment]
The downsides are it means having two modes of behaviour for the warnings depending on whether there are >1 open imports, and I mean that from both a compiler code and user point of view, but I don't think it will be too bad. Perhaps we can include something in the warning message when there are multiple open imports, making it clear that they're occuring because there is more than one open import.

I'm pretty sure it's safe, as the reason we imposed this change was to stop accidental conflicts occur when modules are extended, and since this is only allowed when there is one open module, if we auto-resolve the conflict to the explicit reference we're saved from that case.

**Comment by paf31** [comment]
:+1: Ok sounds good, I'll rename the issue.

**Comment by AppShipIt** [comment]
@garyb Amened `import` proposal:

* `import X` exposes `X.f` and `X.A`
* `import X (A)` exposes `X.f`, `X.A`, and `A`
* `import X (..)` exposes `X.f`, `X.A`, `A`, and `f`
* `import X (..) hiding (f)` exposes `X.f`, `X.A`, and `A` (presumably?)
* `import X as Y` exposes `Y.f` and `Y.A`
* `import X (A) as Y` exposes `Y.A` (right?)
* `import X as Y (A)` is a syntax error

**Comment by paf31** [comment]
Wait, we're not bringing `(..)` back, are we? I hope not.

**Comment by AppShipIt** [comment]
Generating a warning should be explicit. The default behavior shouldn't generate a warning. Furthermore there's currently no way to use an alias without a warning.

**Comment by hdgarrood** [comment]
I'm inclined to agree with @AppShipIt in that we should make the default/easiest path also be the correct one, but perhaps we should see if the single open import approach works before considering changing how `import` works.

**Comment by AppShipIt** [comment]
I'm fine with that especially since it will break things. Discussed offline it additionally provides some missing symmetry:

*  `import X` always introduces an identifier `X`
* `(foo)` additionally introduces `X.foo` as `foo`
* unless `(foo) as Y` introduces `X.foo` as `Y.foo`
* `(..)` is strictly necessary to open an import

And to clarify the breaking changes are:

* `import X` becomes `import X (..)`
* `import X as X` becomes `import X`

**Comment by spicydonuts** [comment]
I like the single open import approach because most files want way more from one import than others (Prelude in most cases, but maybe React.DOM for view modules).  It provides the most brevity while still being safe.  It also never introduces the case where you're reading code and aren't sure where a function was imported from.

Do locally defined functions always override open module imports?  That's the only edge case I can think of where updating dependencies would break things, but you've probably covered that already.

**Comment by AppShipIt** [comment]
> Do locally defined functions always override open module imports?

@spicydonuts Local identifiers always shadow imported ones with a warning.

**Comment by spicydonuts** [comment]
:+1:

**Comment by garyb** [comment]
I don't know why I didn't think of this approach sooner :wink:

**Comment by AppShipIt** [comment]
@garyb Genius 🔮

**Comment by AppShipIt** [comment]
Should I move the `import` one to a new issue?

**Comment by garyb** [comment]
Yes please. Assuming we do go ahead with it, it will be solved separately to the import change anyway.

I'm going to have a look at making this change today too. :dancer:

**Comment by AppShipIt** [comment]
🙌

**Comment by filib** [comment]
Is there any rationale anywhere I can read regarding removal of `(..)` and open imports more generally? 

Currently going through the monotonous task of adding explicit imports and wondering whether, since `purescript-psa` (and presumably `psc`) can tell me what imports I should explicitly include, there should be a tool that can automatically add explicit imports to a project because I can assure you that doing it with my own hands is absolutely no fun at all!

**Comment by spicydonuts** [comment]
@filib psc-ide (now distributed with psc) has a number of editor plugins (emacs, vim, atom) and they support auto-adding explicit imports.  They all support applying a suggestion to an import line (such as making an implicit import explicit) and the newest versions (emacs and atom I believe) support automatically adding imports for you when you first use a function.

**Comment by nwolverson** [comment]
There can certainly be such a tool (to take existing imports and fix them to qualified versions), this functionality is already in IDE plugins (at least it is in the Atom/VS Code ones), and as this is fundamentally from compiler output, there could be a command line tool to generate/apply a diff. The main issue for me there is the poor source position info from the compiler, but with the workarounds already in psa, it should be good enough to output a diff which can be checked.

**Comment by garyb** [comment]
@filib Warning about open imports ensures a module cannot be broken by conflicts coming into scope if new members are added to a module that it imports. This generally isn't a problem within a single library or project, but we've had situations in the past where adding a member to one library broke libraries that depended on it.

And yes, there has been discussion about tooling to help with this, but I don't think there is anything for applying the warning suggestions automatically yet.

**Comment by AppShipIt** [comment]
> removal of `(..)`

Returning in #1901…

> and open imports more generally

But will continue to warn for multiple.

> monotonous task of adding explicit imports

As alluded above got implemented in #1967.

**Comment by filib** [comment]
Whoah! Thanks for such quick replies all!

@nwolverson @spicydonuts that'll certainly help for additive changes. I tried giving `psc-ide` a shot with emacs and atom today but was unable to get either of them to work as they are documented. It's unclear as to whether this was down to my development environment or a particle strike but I'll need to investigate further outside of my working hours.

@AppShipIt @garyb thanks for the context.

**Comment by kRITZCREEK** [comment]
@filib If you could drop into IRC #purescript I could help setting psc-ide up for either Emacs or Atom.
