### ISSUE TITLE
Codegen sometimes omits required instance dictionaries causing runtime failures

### ISSUE THREAD

**Issue by colehaus** [purescript/purescript#3300]
I am seeing inconsistent errors where codegen isn't always providing enough instance dictionaries at call sites. In particular, after a `rm -r output/ .pulp-cache/ && pulp test`, codegen works fine and running the code produces the expected behavior. However, if I then make trivial edits to the file to force it to recompile codegen breaks until I `rm -r output/ .pulp-cache/` again.

In module 1 (a library module), I have:
```purescript
make ::
     forall choice result prob.
     Semiring prob
  => Ord choice
  => Ord result
  => Indexed.NonEmpty Map choice (Dist prob result)
  -> Either (Failure choice result) (SimpleDecisionTree prob choice result)
make map = rmap (const $ MkSimpleDecisionTree map) $ validate map
```

Module 2 (a test module) imports module 1 (as SDT) and calls `make`:
```purescript
genSimpleDecisionTree ::
     forall choice result.
     Ord choice
  => Ord result
  => Indexed.NonEmpty Map choice (NonEmpty Set result)
  -> Gen (SimpleDecisionTree Prob choice result)
genSimpleDecisionTree m =
  unsafeFromRightBecause "Using same skeleton for each" <<<
  SDT.make <$> traverse genDist m
```

In both cases (i.e. when the codegen works and when it doesn't), the called code looks like:
```js
var make = function (dictSemiring) {
    return function (dictOrd) {
        return function (dictOrd1) {
            return function (map) {
                return Data_Bifunctor.rmap(Data_Either.bifunctorEither)(Data_Function["const"](map))(validate(dictOrd)(dictOrd1)(dictSemiring)(map));
            };
        };
    };
};
```

Immediately after a fresh build, the calling code looks like:
```js
var genSimpleDecisionTree = function (dictOrd) {
    return function (dictOrd1) {
        return function (m) {
            return Data_Functor.map(Test_QuickCheck_Gen.functorGen)(function ($55) {
                return Math_Probability_Information_Value_Utility.unsafeFromRightBecause("Using same skeleton for each")(Math_Probability_Information_Value_SimpleDecisionTree.make(Math_Probability_Prob_Number.semiringProb)(dictOrd)(dictOrd1)($55));
            })(Data_Traversable.traverse(Data_NonEmpty_Indexed.traversableNonEmpty(Data_Map.traversableMap))(Test_QuickCheck_Gen.applicativeGen)(genDist(dictOrd1))(m));
        };
    };
};
```
However, if I change an unrelated part of the calling module and recompile the codegen breaks and produces this instead:
```js
var genSimpleDecisionTree = function (dictOrd) {
    return function (dictOrd1) {
        return function (m) {
            return Data_Functor.map(Test_QuickCheck_Gen.functorGen)(function ($55) {
                return Math_Probability_Information_Value_Utility.unsafeFromRightBecause("Using same skeleton for each")(Math_Probability_Information_Value_SimpleDecisionTree.make(dictOrd)(dictOrd1)($55));
            })(Data_Traversable.traverse(Data_NonEmpty_Indexed.traversableNonEmpty(Data_Map.traversableMap))(Test_QuickCheck_Gen.applicativeGen)(genDist(dictOrd1))(m));
        };
    };
};
```
Note that the `semiringProb` instance dictionary is now missing.

The resulting runtime error is a bit misleading but is fundamentally about mismatching arity:

```
Failed pattern match at Math.Probability.Information.Value.Utility line 58, column 1 - line 58, column 64: String,Function
```

**Comment by garyb** [comment]
Is this compiling using the purs ide fast rebuilding? That's the only way I can see something like this occurring - it only rebuilds the single file that was saved, so modifying constraints and things like that on a definition that is called elsewhere will indeed cause problems.

**Comment by colehaus** [comment]
It's happening via `pulp build`. And to be clear, the changes I'm doing to trigger a rebuild never touch constraints. It's stuff like commenting and uncommenting an extra line.

**Comment by garyb** [comment]
Hmm interesting, it's not something I've ever encountered or seen reported before. Is it possible to reduce to a more minimal test case?

**Comment by colehaus** [comment]
Sadly, no. I didn't have much luck paring it down last night and since then I've upgraded my OS. Now I can't reproduce it for whatever reason. I promise it was really happening though!

My only other guess is that `make` used to not require a `Semring prob` constraint (i.e. an hour or so before I encountered this error). So maybe there's some very sneaky caching somewhere that's pulling out the old version?

**Comment by colehaus** [comment]
Actually, I was able to repro something that I assume is similar. Same triggering behavior (fine after clean, broken in subsequent builds) and same symptom (runtime failure due to mismatching arity). The error looks like:

```
  ✗ works for trick coin:

  function (tree) {
                                                return Data_Ring.sub(Data_Functor_Tagged.ringTagged(dictRing))(investigationAndDecisionTreeValue(dictOrd)(dictOrd1)(dictOrd2)(dictOrd3)(dictBounded)(dictSemigroup)(dictSemiring)(project)(decide)(value)(tree))(simpleDecisionTreeValue(dictOrd1)(project)(decide)(value)(forget(dictOrd1)(dictOrd)(dictOrd2)(dictBounded)(dictSemigroup)(dictSemiring)(tree)));
                                            } ≠ 0.5
```

 I've pushed the relevant code to https://github.com/colehaus/purescript-value-of-information/tree/instance-bug. I'll try to pare it down further. If you want to try to repro in the meantime cloning it and then `bower install && pulp test`, followed by a trivial edit in `test/Main.purs` and another `pulp test` should work.

**Comment by colehaus** [comment]
Was able to pare it down quite a bit. This is about as minimal as I can get it: https://github.com/colehaus/purescript-value-of-information/tree/7cc8f85e5af58316e69d2857b864642eafe70f81. Anything further and the problem disappears.

**Comment by garyb** [comment]
I get that error on a clean build! Taking a look now.

**Comment by garyb** [comment]
Oh right, `unsafeCoerce unit` :wink:

**Comment by garyb** [comment]
Ok, I tried on both that commit and the `instance-bug` branch on Windows and OS X, but I'm still not seeing the issue I'm afraid.

**Comment by colehaus** [comment]
Hm. I cloned the code into a fresh directory and performed the repro steps to no avail. Can you think of any extra state or other divergences between a 100% fresh copy of the project (cloned into a new directory) and one with `bower_components`, `.pulp-cache` and `output` removed?

**Comment by colehaus** [comment]
Oooh. So I did have an invocation of `psc ide` running from my editor. I happened to kill the IDE server instance for this project when switching to another project and now I can't reproduce the problem at all. So I'm _very_ suspicious that that's a major factor here. Seems to explain pretty much all the facts (including my earlier failure to repro and then its reappearance). 

Semi-plausible story (`B1->A1` means module B at state 1 references module A at state 1 in a handwavey way): 
1. Module A and B (which imports A) are each at state 1.
```
Purs src: A1 B1->A1
IDE memory: A1 B1
JS out: A1 B1->A1
```
2.  I modify module A to state 2 in some way that the IDE server doesn't pick up (how?).
```
Purs src: A2 B1->A1
IDE memory: A1 B1
JS out: A1 B1->A1
```
3. I modify module B correspondingly to state 2. The IDE server does pick this up. 
```
Purs src: A2 B2->A2
IDE memory: A1 B2
JS out: A1 B2->A1
```
4. A fresh build command (i.e. `rm -r output && pulp test`) looks at the source tree and sees both modules at state 2 and creates a working build.
```
Purs src: A2 B2->A2
IDE memory: A1 B2
JS out: A2 B2->A2
```
5. I modify module B to state 3 (which should be compatible with A's state 2). While editing, the IDE server codegens for B based on its stale in-memory state 1 version of module A.
```
Purs src: A2 B3->A2
IDE memory: A1 B3
JS out: A2 B3->A1
```
6. A "dirty" build (i.e. one that's not preceded by an "rm -r output") picks up the codegen from the IDE server, assumes its work is done and does nothing.
```
Purs src: A2 B3->A2
IDE memory: A1 B3
JS out: A2 B3->A1
```

Of course this all may be fantasy. I don't actually know any of the IDE server internals. If the tables are confusing, just ignore them.

If it's not fantasy, the crucial question is how does the IDE server become desychronized from the source state in step 2. This lays the groundwork for the actual manifested mismatch in 5 and 6.

**Comment by kRITZCREEK** [comment]
I have written up #3323 for this, I don't currently have a solution.
