### ISSUE TITLE
Quick Start Guide fail running pulp build/repl, "Unable to parse module: unexpected "else""

### ISSUE THREAD

**Issue by Michalaq** [purescript/purescript#3367]
The bug is probably due to mismatch of versions between purescript in npm (0.11.7) and libraries downloaded by pulp/bower.

## Steps to reproduce:
```bash
npm install -g purescript bower pulp
mkdir bug
cd bug
pulp init
pulp build  # or pulp repl or pulp psci
```

## Output:
```
Error found:
at bower_components/purescript-psci-support/src/PSCI/Support.purs line 21, column 1 - line 21, column 1

  Unable to parse module:
  unexpected "else"
  expecting declaration or end of input


See https://github.com/purescript/documentation/blob/master/errors/ErrorParsingModule.md for more information,
or to contribute content related to this error.
```

And the related code:

```purescript
-- | ...
instance evalEffect :: Eval a => Eval (Effect a) where
  eval x = x >>= eval
else                            -- | <- This is the referenced line
instance evalShow :: Show a => Eval a where
  eval = logShow
```

## Possible cause:

Mismatch in library version. AFAIK chain instances come with 0.12, but in npm you have only 0.11.7

## Proposed fix:

Either update purescript to 0.12 in npm or update quick start guide pointing to what to do to force pulp/bower download proper versions of libraries for 0.11.7.

Manual solution to get it working is:

```bash
mkdir working
cd working
pulp init
rm -rf bower_components
sed -i "s/4.0.0/3.0.0/g" bower.json
bower install
pulp build   # it now works, along with pulp build and pulp psci
```

But honestly I wouldn't like to have to do this at my first encounter with purescript, following the quick start guide...

**Comment by garyb** [comment]
> But honestly I wouldn't like to have to do this at my first encounter with purescript, following the quick start guide...

Yeah, this happens every time we make a new release / core library ecosystem bump, it's an unfortunate time to be getting started with PureScript. I don't really know how best to fix it.

There is a PR open on the npm package to update it for 0.12, but apparently that will be a few days yet: https://github.com/purescript-contrib/node-purescript/pull/58 (we're not in control of that project)

**Comment by sol** [comment]
I just upgraded to `0.12.0` but it did not result in `pulp bulid` succeeding.

**Comment by garyb** [comment]
Try `purs --version`? You may have 0.11 on your path still.

**Comment by ibnuda** [comment]
Hello, I'm having the same problem.

Currently, the result of `purs --version` is `0.11.7`.
And it was a clean installation.

**Comment by gabejohnson** [comment]
@ibnuda you can download a prebuilt binary from https://github.com/purescript/purescript/releases

**Comment by ibnuda** [comment]
Mr. Johnson,

Unfortunately, when I download that binary, my system reported error:
```
error while loading shared libraries: libtinfo.so.5: cannot open shared object file: No such file or directory
```
And (un)fortunately, the issue itself exclusively related to Arch Linux, so I guess I just have to wait for npm update.

**Comment by gabejohnson** [comment]
@derrickbeining see https://purescript-users.ml/t/working-with-0-11-7-in-a-0-12-world/180

**Comment by Profpatsch** [comment]
> I don't really know how best to fix it.

Well, doesn’t bower use the `^` to say “for `0.*` versions use `0.(*+n)` if available? A language change should be a breaking change, really.

There’s two possible solutions I can think of:
1. Make all PS core-libraries (in the `contrib` group) version `>1.x`
2. Make `bower` somehow not generate "^0.x" version tags for packages starting with `purescript-`. That means this logic would have to be integrated into `pulp` somehow. :frowning_face:

**Comment by hdgarrood** [comment]
> A language change should be a breaking change, really.

0.11.7 -> 0.12 is a breaking change, according to both semver and Haskell's PVP.

Those two suggestions wouldn't solve the problem. (Most libraries are 1.x already, in fact.) The problem is really that a) bower's dependency solving is not smart enough to work well for people who are wanting to stay on library versions intended for use with the compiler version behind the latest, and b) we don't yet have a good way of determining what compiler version a person is intending to use and having build or dependency tools pick that up, so sometimes you'll get library versions which don't match the compiler version you're using.

**Comment by ibnuda** [comment]
Hello everyone,

I've updated `purescript` to `0.12.0` and run `pupl init; pulp build` and then the result is:
```
pulp build                                                                                          ✔  10015  19:09:02 
* Building project in /home/iaji/Sources/Purescript/lemper
Error 1 of 2:

  in module Main
  at src/Main.purs line 4, column 1 - line 4, column 31

    Module Control.Monad.Eff was not found.
    Make sure the source file exists, and that it has been provided as an input to the compiler.


  See https://github.com/purescript/documentation/blob/master/errors/ModuleNotFound.md for more information,
  or to contribute content related to this error.

Error 2 of 2:

  in module Main
  at src/Main.purs line 5, column 1 - line 5, column 48

    Module Control.Monad.Eff.Console was not found.
    Make sure the source file exists, and that it has been provided as an input to the compiler.


  See https://github.com/purescript/documentation/blob/master/errors/ModuleNotFound.md for more information,
  or to contribute content related to this error.


* ERROR: Subcommand terminated with exit code 1
```

**Comment by gabejohnson** [comment]
@ibnuda see the post I linked to above

**Comment by ibnuda** [comment]
Thank you, Mr. Johnson.

I followed Mr. Woo's instructions on his repo and it compiles just fine.

**Comment by joneshf** [comment]
> The problem is really that a) bower's dependency solving is not smart enough to work well for people who are wanting to stay on library versions intended for use with the compiler version behind the latest, and b) we don't yet have a good way of determining what compiler version a person is intending to use and having build or dependency tools pick that up, so sometimes you'll get library versions which don't match the compiler version you're using.

Those are the same problem. And the problem isn't with bower; it's the PS ecosystem. Don't blame bower for libraries under-specifying their dependencies.

Depend on the compiler in `bower.json`, and this entire issue goes away.

**Comment by garyb** [comment]
> Depend on the compiler in `bower.json`, and this entire issue goes away.

What did you have in mind for that?

I'm not sure it would solve the problem either, as bower is truly awful at figuring out versions, aside from installing the latest or what was explicitly stated in a `bower.json`.

**Comment by hdgarrood** [comment]
>  And the problem isn't with bower; it's the PS ecosystem.

No, I promise you that what I said is accurate. I am not the kind of person to throw claims like this around carelessly and I do not appreciate being portrayed as one.

I personally have had bower fail to find an install plan days after my bower.json was created, because just one transitive dependency was updated. This has even happened with the bower.json for the compiler’s test suite, which only uses about half of the core libraries. I have also heard plenty of reports from other users of the same happening.

**Comment by danielo515** [comment]
I'm experiencing this problem with the lates version of everything. Which is the expected fix ? Which versions of purescript-xxx library should I use with 0.12 ?

In which universe the middle digit on semver indicates a mayor release ? What's the purpose of the first digit then ?

**Comment by AlexMouton** [comment]
I can field part of this: 

‘Major version zero (0.y.z) is for initial development. Anything may change at any time. The public API should not be considered stable.’

**Comment by danielo515** [comment]
Ok, so that is because the initial development nature of the project. Got it.

I'm coming back here from the forum post, which in turn directed me to a git repository which helped me to get started with 0.12.0. It has been far from pleasant. Oh, and trying the repl also gave me an error, which pointed me to another github repository (PSCi) with outdated documentation about how to install the repl. I installed it through pscp-package, which have added it to my dependencies, not sure if this is going to bloat my final build.

So far I have installed bower (which I really hate) psc-package (which I think makes bower totally useless) purescript and pulp from npm, cloned a repository and installed one library from pscp.
It is being very confusing because almost 100% of the documentation is outdated for 0.12.0 version. Maybe it would be a great idea to fix the manuals ton install `npm i purescript@0.11.x` rather than the latest version.

Regards

**Comment by Profpatsch** [comment]
> It is being very confusing because almost 100% of the documentation is outdated for 0.12.0 version. Maybe it would be a great idea to fix the manuals ton install npm i purescript@0.11.x rather than the latest version.

I understand that you are salty, but the project is still very young, so the mechanisms for seamless updates between breaking versions is not yet in place (that’s why it’s `0.12`, not `1.1` or similar).

**Comment by danielo515** [comment]
Hello @Profpatsch , you're right
That's because we can not rely on manual updates that involves human work. In my opinion locking the documentation down to an specific version is the easiest way.

Some other thing that it will be very beneficial is to force the libraries to specify which version of PS they work with, it's being a very difficult task to select the proper ones

**Comment by javinor** [comment]
Hey guys!

As an experienced JS dev, and Haskell enthusiast, I just started to play around with `purescript` and the project looks really promising, kudos!

I too encountered the whole versioning problem (`0.12.0` doesn't play well with the VSCode extension...). What would you prefer doing: updating the docs to `0.12.0` or maybe changing the `getting started` guide by locking it on `0.11.7`? I don't mind opening a PR for it myself, just let me know where you want to take it...

Keep up the great job!

**Comment by monkeygroover** [comment]
> Yeah, this happens every time we make a new release / core library ecosystem bump, it's an unfortunate time to be getting started with PureScript. I don't really know how best to fix it.

You don't necessarily need to actually fix it;  I feel the pain of trying to manage breaking changes in such a young project, but something simple to manage user expectations like a warning on the purescript homepage indicating that there are currently problems with examples and quickstarts due to 0.12 would go a long way to reassure people who unfortunately choose this moment of flux to start their purescript journey :)

**Comment by LiamGoodacre** [comment]
Closing as the original issue has been solved.

**Comment by bitterjug** [comment]
What was the fix! The https://purescript-users.ml/t/working-with-0-11-7-in-a-0-12-world/180 article no longer exists.

**Comment by justinwoo** [comment]
@bitterjug try https://discourse.purescript.org/t/working-with-0-11-7-in-a-0-12-world/180

**Comment by stevematdavies** [comment]
Still not worlking, either bowere or psc. Havent managed to get a purescript app up and running yet.

**Comment by JordanMartinez** [comment]
In case others come across this issue, there's a few things one can do:
- after creating a purescript project, install the `[purescript-psci-support](https://github.com/purescript/purescript-psci-support)` package. Otherwise, the REPL will not work. 
- for up-to-date documentation, consider checking out my learning repository which is designed to be `git clone`d with projects already properly configured, so you don't have to deal with this build confusion: [Purescript: Jordan's Reference](https://github.com/jordanmartinez/purescript-jordans-reference)

**Comment by hdgarrood** [comment]
I don't think those suggestions are related to this issue; the issue here is that people can sometimes end up trying to use 0.11.x versions of the compiler together with libraries which are intended for use with 0.12.x. The fix (as stated in the original issue) is to update your `purs` executable to 0.12.x.

**Comment by JordanMartinez** [comment]
Mm... Sorry about that post then. I'll edit the post to refer to what you say after it. 
This issue was rather long, so I didn't read through all of it. Since Steve posted in other similar threads, I thought the `psci-support` was the solution.

**Comment by stevematdavies** [comment]
I have the latest version of purs etc. Anyhow, if the installation instructions dont specify providing any particular version label  at install time , then why wouldn't the latest version be installed ?
